### ISSUE TITLE
RadAutoCompleteTextView: Angular: Clicking on tokens mark them with blue color

### ISSUE THREAD

**Issue by danim87** [ProgressNS/nativescript-ui-feedback#1305]
First of all thanks for all ur work guys!

> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Tell us about the problem
When I click one of the tokens or more, all clicked tokens get blue and the sof keyboard opens up. If its already open it switches from uppercase to lowercase.
I would like to stop this behavior - I just dont want the user to be able to click on the tokens 
-> what means the tokenbs shouldnt be marked blue and the keyboard shouldnt be triggered. 

### Which platform(s) does your issue occur on?
_iOS/ 13.1 iPhone 11 Pro Max

I am using nativescript-angular -> "nativescript-angular": "~8.0.0"

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI plugin version:** "nativescript-ui-autocomplete": "^5.1.1",
- **CLI:** cli: 6.2.1
- **Cross-platform modules: " tns-core-modules": "~6.1.2"
- **Runtime(s):** tns-ios": "version": "6.1.1"

### Please tell us how to recreate the issue in as much detail as possible.
1. Run the autocomplete in displaymode token
2. add a token
3. click/touch on the token
4. it gets blue, softkeyboard gets fired up

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

It is just present in the given examples

https://github.com/NativeScript/nativescript-ui-samples-angular/tree/master/autocomplete

**Comment by tsonevn** [comment]
HI @danielmoenius,
In your scenario, you can disable the user interaction for the tokens by adding the following code in your CSS:
```
RadAutoCompleteTextView Token {
    is-user-interaction-enabled: false;
}
```
