### ISSUE TITLE
RadListView 'loadMoreDataRequested' problem

### ISSUE THREAD

**Issue by DimitrisRK** [ProgressNS/nativescript-ui-feedback#1369]
RadListView 'loadMoreDataRequested' and 'pullToRefreshInitiated' callbacks are never called if set with curly braces inside XML, which is really weird. This occurs regardless of the type of demand mode. I'm using plain JS.

Platforms: Android

Progress NativeScript UI plugin version: nativescript-ui-listview 8.0.1
CLI: 6.4.1
Cross-platform modules: 6.4.2
Runtime: Android 6.4.1

How to recreate: Just try calling a function from page JS file with curly braces and without them. Here is an example with 'loadMoreDataRequested':
Not Working: `<lv:RadListView items="{{ data }}" loadOnDemandMode="Manual" loadMoreDataRequested="{{ callback }}">`
Works: `<lv:RadListView items="{{ data }}" loadOnDemandMode="Manual" loadMoreDataRequested="callback">`

**Comment by NickIliev** [comment]
@DimitrisRK are you sure you are having the callback in the view model and the view model created and as the binding context for your current page (the one that holds the calendar).

We are having multiple examples that are using view model binding (curly braces) [here  ](https://github.com/NativeScript/nativescript-ui-samples/search?q=loadMoreDataRequested&unscoped_q=loadMoreDataRequested) and they are working as expected.

**Comment by DimitrisRK** [comment]
Since when is that the case? I'm pretty sure that callbacks can also be used from page js file if exported. That's how it's been until now.
Also, adding callback to view model didn't do a thing.
