### ISSUE TITLE
Unable to run app with nativescript-ui-sidedrawer

### ISSUE THREAD

**Issue by earnestware** [ProgressNS/nativescript-ui-feedback#1465]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Tell us about the problem
Canno run app after adding nativescript-ui-sidedrawer

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- nativescript-ui-sidedrawer/^9.0.3
- **CLI:** 6.8.1
- **Cross-platform modules:** ^6.5.16
- **Runtime(s):** both 6.5.0

### Please tell us how to recreate the issue in as much detail as possible.
1. Follow instructions here: https://docs.nativescript.org/angular/ui/ng-components/ng-sidedrawer/getting-started
2. run tns plugin add nativescript-ui-sidedrawer
3. add import { NativeScriptUISideDrawerModule } from "nativescript-ui-sidedrawer/angular"; to app.module.ts
4. add NativeScriptUISideDrawerModule to imports section
5. run either tns run android or tns run ios
6. errors.
They both emit the same error. Either some information from the docs is missing or I missed something.. 

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
IOS -error start with 
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x10269b60e NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x1026ed5f4 -[TNSRuntime executeModule:referredBy:]
3   0x101f75303 main
4   0x7fff5211c1fd start
5   0x1
JavaScript stack trace:
../node_modules/nativescript-ui-sidedrawer/ui-sidedrawer.common.js(file: node_modules/nativescript-ui-sidedrawer/ui-sidedrawer.common.js:27:66)
at __webpack_require__(file: src/webpack/bootstrap:750:0)

Android - errors start with 
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: Class extends value undefined is not a constructor or null
System.err: File: (file: node_modules/nativescript-ui-sidedrawer/ui-sidedrawer.common.js:27:66)
System.err: 
System.err: StackTrace: 
System.err: ../node_modules/nativescript-ui-sidedrawer/ui-sidedrawer.common.js(file: node_modules/nativescript-ui-sidedrawer/ui-sidedrawer.common.js:27:66)
System.err:     at __webpack_require__(file: src/webpack/bootstrap:750:0)
System.err:     at fn(file: src/webpack/bootstrap:120:0)
System.err:     at (file: node_modules/nativescript-ui-sidedrawer/ui-sidedrawer.android.js:1:0)
System.err:     at ../node_modules/nativescript-ui-sidedrawer/ui-sidedrawer.js(file:///data/data/org.nativescript.GuardSchedules/files/app/vendor.js:147798:30)
System.err:     at __webpack_require__(file: src/webpack/bootstrap:750:0)
System.err:     at fn(file: src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/nativescript-ui-sidedrawer/angular/fesm2015/nativescript-ui-sidedrawer-angular.js(file: node_modules/nativescript-ui-sidedrawer/angular/fesm2015/nativescript-ui-sidedrawer-angular.js:1:0)
System.err:     at __webpack_require__(file: src/webpack/bootstrap:750:0)
System.err:     at fn(file: src/webpack/bootstrap:120:0)
System.err:     at ./app/app.module.ts(file: src/app/app.module.ts:1:0)
System.err:     at __webpack_require__(file: src/webpack/bootstrap:750:0)
System.err:     at fn(file: src/webpack/bootstrap:120:0)
System.err:     at (file:///data/data/org.nativescript.GuardSchedules/files/app/bundle.js:165:73)
System.err:     at ./main.ts(file:///data/data/org.nativescript.GuardSchedules/files/app/bundle.js:224:30)
System.err:     at __webpack_require__(file: src/webpack/bootstrap:750:0)
System.err:     at checkDeferredModules(file: src/webpack/bootstrap:43:0)
System.err:     at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
System.err:     at (file:///data/data/org.nativescript.GuardSchedules/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err:

**Comment by earnestware** [comment]
just discovered that i can create an app using the template command "tns create --template tns-template-drawer-navigation-ng" and this works.

**Comment by adityadi98** [comment]
But what if I installed it in an ongoing project ...it gives errors... did you find any solutions to this
